### PR TITLE
chore: updates all deps and adds types

### PR DESCRIPTION
**Pull request by achingbrain**
Updates to the latest version of all deps and adds types.

BREAKING CHANGE: There are now types where before there were none

### CODE REVIEW

**Review by alanshaw — APPROVED** [review]

**Comment by alanshaw** [comment]
Adding types is breaking? 🧐

**Comment by achingbrain** [comment]
Only in that people who use a given module may find that the API they’ve coded against isn’t the actual API after all. It’s generally safer to release as a major..

**Comment by achingbrain** [comment]
Can this be merged & released please?  I think you're the only one with npm perms for this module..

**Comment by alanshaw** [comment]
@hugomrdias is a maintainer also - added you too @achingbrain.

**Comment by achingbrain** [comment]
Ah, thanks - only your name came up with `npm owner ls cid-tool`

**Pull request merged**
